spring.application.name=java_server

#Multipart configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Facial Recognition Configuration
# i have temporarily disabled  facialrecognition to false. Set to true to enable facial recognition (requires OpenCV native libraries)
facial.recognition.enabled=true
